from .system_prompts import (
    AGENT_SYSTEM_PROMPT,
    ANALIZADOR_TEMARIO_PROMPT,
    COORDINADOR_GENERAL_PROMPT,
    CALIBRADOR_PROMPT,
    FUENTES_NORMATIVAS_PROMPT,
    REVISION_NUMERICA_PROMPT,
    REDACTOR_ESPECIALISTA_PROMPT,
    PNL_PEDAGOGICO_PROMPT,
    REVISION_CALIDAD_PROMPT,
    COHERENCIA_BLOQUE_PROMPT,
    GENERADOR_TESTS_PROMPT,
    MAQUETADOR_PROMPT,
)
